### ISSUE TITLE
WHMCS 71

### ISSUE THREAD

**Issue by ilovebamboo** [Zzm317/V2raySocks#1]
![2018-05-28 11 45 25](https://user-images.githubusercontent.com/6214084/40596320-a2e30bc4-626c-11e8-8935-71e0f3de89c7.jpg)
无法打开不显示

**Comment by Zzm317** [comment]
请把放入modules/servers里面。。

**Comment by ilovebamboo** [comment]
非常感谢，已经搭好了，
![qq20180529-175301](https://user-images.githubusercontent.com/6214084/40651801-297c493c-6369-11e8-978b-783f57ba0287.png)
现在的问题是用 那个V2RAY后端安装后台？
自动任务执行命令是什么 ？有没有啊？

**Comment by Zzm317** [comment]
自动任务是跟随whmcs的自动任务的 不需要自行配置
manager需要购买 https://t.me/V2rayIsNotGreat
