### ISSUE TITLE
大神，配套的后端呢？

### ISSUE THREAD

**Issue by ouyangrui** [Zzm317/V2raySocks#2]
如题，教程有没有一个

**Comment by Zzm317** [comment]
后端需要购买
请前往 https://t.me/V2rayIsNotGreat 获取购买详情
插件安装教程 https://www.loli.ren/archives/108/

**Comment by ilovebamboo** [comment]
无售后 体验不行

**Comment by Zzm317** [comment]
请先说明你上的是私家车还是合购车
私家车如果需要帮助可能我态度差点但是基本都会说一下哪里问题或者如何解决
合购车 你摸摸你的良心说说合购价格你还好意思要多好的售后？
实际上我现在不管合购还是私家车 提了需要更新的我都会更新 但是不看聊天 或者不提需求 或者刚过来就丢一个 我不会配tls 我不会怎么样 你给我弄的 我管你私家车还是合购车 你这都不是问我manager问题了我为什么给你解决啊
