### ISSUE TITLE
线路列表中的选项怎么填？

### ISSUE THREAD

**Issue by shenzt68** [Zzm317/V2raySocks#7]
格式 xxx|服务器地址|端口|伪装类型|tls|host|路径|传输协议|流量倍率|额外id 一行一个，不支持留空
其中：伪装类型|tls|host|路径|传输协议，这些怎么填？说明不清啊

**Comment by Zzm317** [comment]
www.v2ray.com
不清楚的话就 HK1|127.0.0.1|12800|none||||tcp|1|32
这些都是v2ray基础配置内容，请自己查阅v2ray官网了解

**Comment by shenzt68** [comment]
不是不支持留空吗？

**Comment by Zzm317** [comment]
留空的意思就是让你那个空不填

**Comment by Zzm317** [comment]
有些东西是不能留空的
请参阅www.v2ray.com v2ray官网

**Comment by shenzt68** [comment]
伪装类型是什么？

**Comment by Zzm317** [comment]
请你下载个v2rayn什么的客户端看看再来问谢谢
部分翻译是基于各种客户端来的 不知道就别写 那么简单的事情

**Comment by Zzm317** [comment]
一句话 不知道别写 我不负责任何种类的教学 翻译问题别问我 问客户端开发者
